---
# We generate the vault config
- name: config | Configuring HashiCorp Vault
  template:
    src: "vault.hcl.j2"
    dest: "{{ hashi_vault_config }}"
    owner: "root"
    group: "{{ hashi_vault_user_info['group'] }}"
    mode: "u=rw,g=r,o=r"
  notify:
    - "restart vault-server"
    - "init"

# We give the Vault executable the ability to use the mlock syscall
# without running the process as root
- name: config | Granting {{ hashi_vault_user_info['user'] }} mlock syscall
  capabilities:
    path: "{{ hashi_vault_install_dir }}/vault"
    capability: "cap_ipc_lock+ep"
    state: "present"
  notify:
    - "restart vault-server"
    - "init"
  when: not ansible_check_mode
